### ISSUE TITLE
Could you tell me which paper corresponds to this code?

### ISSUE THREAD

**Issue by weigangwen** [Somendratripathi/ICCV_Autonomous-Driving#3]
Hello, I am very interested in this code . Could you tell me which paper corresponds to this code?

**Comment by submagr** [comment]
Hi @weigangwen,
Glad you liked the project.

It was a course project. Following links might be useful:
- Project Handout: https://drive.google.com/file/d/1BQ7FWPgoLEtEjtIP0nYrZJhu04R0UayW/view?usp=sharing
- Our report: https://drive.google.com/file/d/1Na7WOjQSmxjariMvHu62Ak6CgQvILV21/view?usp=sharing
- Competition Website: https://www.aicrowd.com/challenges/iccv-2019-learning-to-drive-challenge#learning-to-drive-challenge

**Comment by weigangwen** [comment]
Thank you very much for sharing！

**Comment by weigangwen** [comment]
Thank you very much for sharing！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Somendratripathi/ICCV_Autonomous-Driving"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月14日(星期三) 下午2:19
收件人:&nbsp;"Somendratripathi/ICCV_Autonomous-Driving"<ICCV_Autonomous-Driving@noreply.github.com&gt;;
抄送:&nbsp;"gangwen Wei"<1595931419@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [Somendratripathi/ICCV_Autonomous-Driving] Could you tell me which paper corresponds to this code? (#3)





 
Hi @weigangwen,
 Glad you liked the project.
 
It was a course project. Following links might be useful:
  
Project Handout: https://drive.google.com/file/d/1BQ7FWPgoLEtEjtIP0nYrZJhu04R0UayW/view?usp=sharing
 
Our report: https://drive.google.com/file/d/1Na7WOjQSmxjariMvHu62Ak6CgQvILV21/view?usp=sharing
 
Competition Website: https://www.aicrowd.com/challenges/iccv-2019-learning-to-drive-challenge#learning-to-drive-challenge
